config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users

  # get 'users/index
  # get 'users/new'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # get 'indexnew/edit'
  # get 'indexnew/update'
  # get 'indexnew/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 }, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :age, presence: true, length: { maximum: 2 }, format: { with: /[0-9]/, message: "enter valid age" }
  validates :gender, presence: true
  enum gender: { male: 0, female: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other 
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserData</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  
  <div>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div><br>
  
  <div>
    <%= form.label :Age %><br>
    <%= form.text_field :age %>
    <% @user.errors.full_messages_for(:age).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div><br>

  <%= form.label :gender , for: :gender %>
  <div class="container">
    <%= form.radio_button :gender, 'female' %>
    <%= form.label :gender,'Female',value: 'female'%>
    <%= form.radio_button :gender, 'male' %>
    <%= form.label :gender,'Male',value: 'male'%><br>
    <% @user.errors.full_messages_for(:gender).each do |message| %><br>
      <div class="error"><%= message %></div>
    <% end %>
  </div><br><br>

  <%= form.submit %>
<% end %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2>Update user:</h2>

<%= render "form", user: @users %>

app/views/users/index.html.erb
<header><p>User application</p></header>
<body>
<h1>User Details</h1>

<table>
  <thead>
    <th>Name</th>
    <th>Age</th>
    <th>Gender</th> 
    <th>Edit</th> 
    <th>Delete</th> 
  </thead>
  <tbody>
    <% @users .each do |u| %>
    <tr>
      <td><%=u.name%></td>
      <td><%=u.age%></td>
      <td><%=u.gender%></td>
      <td><%= link_to "Edit",edit_user_path(u) %></td>
      <td><%= link_to "Destroy", user_path(u), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></ul></td>
    </tr>
    <% end %>
  </tbody> 
</table><br>

<%= link_to "New user",new_user_path %><br>

</body>

app/views/users/new.html.erb
<h2>Add new user</h2>

<%= render "form", user: @users %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>